name: Python application test with Github Actions using python 3.5
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.3
      - name: Install dependencies
        run: |
          make install
      - name: Lint with Pylint
        run: |
          make lint
      - name: Test with Pytest
        run: |
          make test
      - name: Format with Python Black
        run: |
          make format
